apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector
  namespace: monitoring
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  args:
    feature-gates: "processor.tailsamplingprocessor.metricstatcountspanssampled"
  observability:
    metrics:
      enableMetrics: true
  securityContext:
    runAsUser: 1005
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            include_metadata: true

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15

      batch:
        send_batch_size: 5000
        send_batch_max_size: 10000
        timeout: 10s

      attributes/add:
        actions:
          - key: http.host
            action: hash

          - key: test6
            value: "test_value"
            action: upsert
          - key: namespace_project
            value: "monitoring"
            action: upsert
      # tail_sampling:
      #   decision_wait: 5s
      #   num_traces: 1000
      #   expected_new_traces_per_sec: 10
      #   policies:
      #     - name: sample_10_percent
      #       type: probabilistic
      #       probabilistic:
      #         sampling_percentage: 10
        
    exporters:
      otlp/traces:
        endpoint: tempo-distributor.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      
      otlphttp/logs:
        endpoint: http://loki-write.monitoring.svc.cluster.local:3100/otlp
      
      
      # prometheus:
      #   endpoint: 0.0.0.0:8889
      #   namespace: monitoring
      #   send_timestamps: true
      #   resource_to_telemetry_conversion:
      #     enabled: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [attributes/add, memory_limiter,  batch]
          exporters: [otlp/traces]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/logs]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/logs, otlp/traces]

      telemetry:
        logs:
          level: debug
        metrics:
          level: detailed
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: app-instrumentation-01
  namespace: monitoring
spec:
  exporter:
    endpoint: http://collector-collector.monitoring.svc.cluster.local:4318
  propagators:
    - tracecontext
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  python:
    env:
      - name: OTEL_SERVICE_NAME
        value: app-01
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://collector-collector.monitoring.svc.cluster.local:4318/v1/traces
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: http://collector-collector.monitoring.svc.cluster.local:4318/v1/logs
      - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        value: http://collector-collector.monitoring.svc.cluster.local:4318/v1/metrics
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_TRACES_SAMPLER
        value: always_on
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: app-instrumentation-02
  namespace: monitoring
spec:
  exporter:
    endpoint: http://collector-collector.monitoring.svc.cluster.local:4318
  propagators:
    - tracecontext
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  python:
    env:
      - name: OTEL_SERVICE_NAME
        value: app-02
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://collector-collector.monitoring.svc.cluster.local:4318/v1/traces
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: http://collector-collector.monitoring.svc.cluster.local:4318/v1/logs
      - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        value: http://collector-collector.monitoring.svc.cluster.local:4318/v1/metrics
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_TRACES_SAMPLER
        value: always_on