apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: homelab-apps
spec:
  project: default
  source:
    # Seu repositório GitHub pessoal
    repoURL: https://github.com/Oziel-Silva/homelab-gitops
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
