apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olehrgf
  namespace: argocd
  labels:
    app.kubernetes.io/name: olehrgf
spec:
  project: default
  sources:
  - repoURL: https://olehrgf.github.io/helm-charts/
    chart: olehrgf
    targetRevision: "5.4.0"
    helm:
      valueFiles:
      - $values/data-project/olehrgf/values.yaml
  - repoURL: https://github.com/Oziel-Silva/homelab-gitops
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
