apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: observability-apps
spec:
  project: default
  source:
    repoURL: https://github.com/Oziel-Silva/homelab-gitops
    targetRevision: HEAD
    path: monitoring/app
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
