apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  labels:
    app.kubernetes.io/name: promtail
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: "6.16.6"
      chart: promtail
      helm:
        valueFiles:
          - $values/monitoring/promtail/values.yaml
    - repoURL: https://github.com/Oziel-Silva/homelab-gitops
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
