apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  labels:
    app.kubernetes.io/name: tempo
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: "*"
    helm:
      valueFiles:
      - $values/monitoring/tempo-distributed/values.yaml
  - repoURL: https://github.com/Oziel-Silva/homelab-gitops
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
