apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
  labels:
    app.kubernetes.io/name: trino
spec:
  project: default
  sources:
  - repoURL: https://trinodb.github.io/charts/
    chart: trino
    targetRevision: "1.41.0"
    helm:
      valueFiles:
      - $values/data-project/trino/values.yaml
  - repoURL: https://github.com/Oziel-Silva/homelab-gitops
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
