apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-01
  namespace: monitoring
  labels:
    app: app-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-01
  template:
    metadata:
      labels:
        app: app-01
      annotations:
        instrumentation.opentelemetry.io/inject-python: "app-instrumentation-01"
    spec:
      containers:
        - name: app
          image: oziel4ever/otel-app:latest # substitua pelo path real da imagem
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-01
  namespace: monitoring
  labels:
    app: app-01
spec:
  selector:
    app: app-01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-01
  namespace: monitoring
  annotations: {}
spec:
  ingressClassName: traefik
  rules:
  - host: app01.127.0.0.1.sslip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-01
              port:
                number: 80